### ISSUE TITLE
시그네쳐값

### ISSUE THREAD

**Issue by aspone17** [RyuaNerin/ffchat#1]
혹시 시그네쳐값을 어떻게 잡으셨는지 알 수 있을까요?

**Comment by RyuaNerin** [comment]
파판 인벤에 올라오는 파일을 추출하여 사용했습니다

**Comment by aspone17** [comment]
아하~
제가 글섭에서 이걸 이용하고 있는데 내일 4.0 나와서 운이 나쁘면 클라이언트 시그네처가 바뀔 것 같아서요.
혹시 치트엔진으로 일일히 찾아봐야 하는 걸까요? 어떤 파일을 보면 될까요?

**Comment by RyuaNerin** [comment]
저도 그 부분은 잘 모르겠습니다. 직접 찾기 귀찮아서 미터기에서 사용한 방법을 추출한거라ㅠㅠ

**Comment by aspone17** [comment]
흐음 그렇군요 답변해주셔서 고맙습니다.

**Comment by aspone17** [comment]
혹시 참고할만한 자료나 코드가 있을까요? 4.0에서 시그네쳐값은 변함이 없는 것 같은데 오프셋 값이 달라진 것 같네요.

**Comment by RyuaNerin** [comment]
ACT_FFXIV_PLUGIN 이랑 동일한 코드를 사용합니다.

**Comment by aspone17** [comment]
감사합니다 :)
